// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: wf_ui

#include "../ui.h"

lv_obj_t *uic_batteryIcon;
lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Container2 = NULL;lv_obj_t *ui_Container6 = NULL;lv_obj_t *ui_Image1 = NULL;lv_obj_t *ui_numNoti = NULL;lv_obj_t *ui_Container7 = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_batteryIcon = NULL;lv_obj_t *ui_TimeContainer = NULL;lv_obj_t *ui_HourLabel = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_MinuteLabel = NULL;lv_obj_t *ui_Container3 = NULL;lv_obj_t *ui_Image2 = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_Container4 = NULL;lv_obj_t *ui_day1 = NULL;lv_obj_t *ui_day2 = NULL;lv_obj_t *ui_day3 = NULL;lv_obj_t *ui_day4 = NULL;lv_obj_t *ui_day5 = NULL;lv_obj_t *ui_day6 = NULL;lv_obj_t *ui_day7 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container2 = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_width( ui_Container2, 154);
lv_obj_set_height( ui_Container2, 24);
lv_obj_set_x( ui_Container2, 5 );
lv_obj_set_y( ui_Container2, -69 );
lv_obj_set_align( ui_Container2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container6 = lv_obj_create(ui_Container2);
lv_obj_remove_style_all(ui_Container6);
lv_obj_set_width( ui_Container6, 75);
lv_obj_set_height( ui_Container6, 24);
lv_obj_set_align( ui_Container6, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container6,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image1 = lv_image_create(ui_Container6);
lv_image_set_src(ui_Image1, &ui_img_1156340770);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_Image1, -251 );
lv_obj_set_y( ui_Image1, 99 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_numNoti = lv_label_create(ui_Container6);
lv_obj_set_width( ui_numNoti, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_numNoti, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_numNoti, LV_ALIGN_CENTER );
lv_label_set_text(ui_numNoti,"10");

ui_Container7 = lv_obj_create(ui_Container2);
lv_obj_remove_style_all(ui_Container7);
lv_obj_set_width( ui_Container7, 75);
lv_obj_set_height( ui_Container7, 24);
lv_obj_set_align( ui_Container7, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container7,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label5 = lv_label_create(ui_Container7);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"90%");
lv_obj_set_style_pad_left(ui_Label5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label5, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batteryIcon = lv_image_create(ui_Container7);
lv_image_set_src(ui_batteryIcon, &ui_img_battery_status_4_png);
lv_obj_set_width( ui_batteryIcon, 24);
lv_obj_set_height( ui_batteryIcon, 24);
lv_obj_set_x( ui_batteryIcon, 28 );
lv_obj_set_y( ui_batteryIcon, -64 );
lv_obj_set_align( ui_batteryIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_batteryIcon, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_batteryIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TimeContainer = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_TimeContainer);
lv_obj_set_width( ui_TimeContainer, 144);
lv_obj_set_height( ui_TimeContainer, 64);
lv_obj_set_x( ui_TimeContainer, 2 );
lv_obj_set_y( ui_TimeContainer, -19 );
lv_obj_set_align( ui_TimeContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_TimeContainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_TimeContainer, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_TimeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HourLabel = lv_label_create(ui_TimeContainer);
lv_obj_set_width( ui_HourLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HourLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HourLabel, -51 );
lv_obj_set_y( ui_HourLabel, -10 );
lv_obj_set_align( ui_HourLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_HourLabel,"10");
lv_obj_remove_flag( ui_HourLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE );    /// Flags
lv_obj_set_style_text_color(ui_HourLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_HourLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HourLabel, &ui_font_sevensegments, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_HourLabel, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HourLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HourLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_HourLabel, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_HourLabel, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_HourLabel, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_HourLabel, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_TimeContainer);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, -21 );
lv_obj_set_y( ui_Label4, -12 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,":");
lv_obj_set_style_text_font(ui_Label4, &ui_font_sevensegments, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_USER_1);

ui_MinuteLabel = lv_label_create(ui_TimeContainer);
lv_obj_set_width( ui_MinuteLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MinuteLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MinuteLabel, 6 );
lv_obj_set_y( ui_MinuteLabel, -12 );
lv_obj_set_align( ui_MinuteLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_MinuteLabel,"11");
lv_obj_set_style_text_font(ui_MinuteLabel, &ui_font_sevensegments, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container3 = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container3);
lv_obj_set_width( ui_Container3, 130);
lv_obj_set_height( ui_Container3, 32);
lv_obj_set_x( ui_Container3, 12 );
lv_obj_set_y( ui_Container3, 31 );
lv_obj_set_align( ui_Container3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container3,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image2 = lv_image_create(ui_Container3);
lv_image_set_src(ui_Image2, &ui_img_sun_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_Image2, -42 );
lv_obj_set_y( ui_Image2, 36 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label6 = lv_label_create(ui_Container3);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"Feb, 14 2026");
lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label6, &ui_font_NotoSansCondensedMedium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container4 = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container4);
lv_obj_set_width( ui_Container4, 164);
lv_obj_set_height( ui_Container4, 22);
lv_obj_set_x( ui_Container4, 0 );
lv_obj_set_y( ui_Container4, 63 );
lv_obj_set_align( ui_Container4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container4,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_day1 = lv_label_create(ui_Container4);
lv_obj_set_width( ui_day1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_day1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_day1, LV_ALIGN_CENTER );
lv_label_set_text(ui_day1,"09");

ui_day2 = lv_label_create(ui_Container4);
lv_obj_set_width( ui_day2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_day2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_day2, LV_ALIGN_CENTER );
lv_label_set_text(ui_day2,"10");

ui_day3 = lv_label_create(ui_Container4);
lv_obj_set_width( ui_day3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_day3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_day3, LV_ALIGN_CENTER );
lv_label_set_text(ui_day3,"11");

ui_day4 = lv_label_create(ui_Container4);
lv_obj_set_width( ui_day4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_day4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_day4, LV_ALIGN_CENTER );
lv_label_set_text(ui_day4,"12");

ui_day5 = lv_label_create(ui_Container4);
lv_obj_set_width( ui_day5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_day5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_day5, LV_ALIGN_CENTER );
lv_label_set_text(ui_day5,"13");

ui_day6 = lv_label_create(ui_Container4);
lv_obj_set_width( ui_day6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_day6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_day6, LV_ALIGN_CENTER );
lv_label_set_text(ui_day6,"14");
lv_obj_set_style_text_color(ui_day6, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_day6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_day6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_day6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_day6, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_day7 = lv_label_create(ui_Container4);
lv_obj_set_width( ui_day7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_day7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_day7, LV_ALIGN_CENTER );
lv_label_set_text(ui_day7,"15");
lv_obj_set_style_text_color(ui_day7, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_day7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

uic_batteryIcon = ui_batteryIcon;

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Container2= NULL;
ui_Container6= NULL;
ui_Image1= NULL;
ui_numNoti= NULL;
ui_Container7= NULL;
ui_Label5= NULL;
uic_batteryIcon= NULL;
ui_batteryIcon= NULL;
ui_TimeContainer= NULL;
ui_HourLabel= NULL;
ui_Label4= NULL;
ui_MinuteLabel= NULL;
ui_Container3= NULL;
ui_Image2= NULL;
ui_Label6= NULL;
ui_Container4= NULL;
ui_day1= NULL;
ui_day2= NULL;
ui_day3= NULL;
ui_day4= NULL;
ui_day5= NULL;
ui_day6= NULL;
ui_day7= NULL;

}
