// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: wf_ui

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_Container6;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_numNoti;
extern lv_obj_t *ui_Container7;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_batteryIcon;
extern lv_obj_t *ui_TimeContainer;
extern lv_obj_t *ui_HourLabel;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_MinuteLabel;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Container4;
extern lv_obj_t *ui_day1;
extern lv_obj_t *ui_day2;
extern lv_obj_t *ui_day3;
extern lv_obj_t *ui_day4;
extern lv_obj_t *ui_day5;
extern lv_obj_t *ui_day6;
extern lv_obj_t *ui_day7;
// CUSTOM VARIABLES
extern lv_obj_t *uic_batteryIcon;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

