// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: wf_ui

#include "../ui.h"

lv_obj_t *ui_Screen2 = NULL;lv_obj_t *ui_Container1 = NULL;lv_obj_t *ui_title = NULL;lv_obj_t *ui_content = NULL;lv_obj_t *ui_Container5 = NULL;lv_obj_t *ui_Label3 = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_Screen2,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Screen2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);

ui_Container1 = lv_obj_create(ui_Screen2);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, 160);
lv_obj_set_height( ui_Container1, 142);
lv_obj_set_x( ui_Container1, -57 );
lv_obj_set_y( ui_Container1, 13 );
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_title = lv_label_create(ui_Container1);
lv_obj_set_width( ui_title, 160);
lv_obj_set_height( ui_title, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_title, LV_ALIGN_CENTER );
lv_label_set_text(ui_title,"text");
lv_obj_set_style_text_color(ui_title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_title, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_title, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_title, &ui_font_NotoSansCondensedMedium, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_title, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_title, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_title, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_content = lv_label_create(ui_Container1);
lv_obj_set_width( ui_content, 170);
lv_obj_set_height( ui_content, 111);
lv_label_set_text(ui_content,"Thủ tướng Campuchia hy vọng Hội đồng Hòa bình do Tổng thống Trump khởi xướng sẽ giúp nước này và Thái Lan hạ nhiệt căng thẳng.\n\n\"Chúng tôi tin Hội đồng Hòa bình là sự bổ sung đáng giá cho những cơ chế hiện có của các tổ chức quốc tế nhằm thúc đẩy hòa bình, ổn định, cũng như xây dựng và bảo đảm hòa bình tại nhiều khu vực đang bị ảnh hưởng hoặc đe dọa bởi chiến tranh và xung đột\", Thủ tướng Campuchia Hun Manet trả lời Reuters ngày 17/2.");
lv_obj_set_style_text_font(ui_content, &ui_font_NotoSansCondensedMedium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container5 = lv_obj_create(ui_Screen2);
lv_obj_remove_style_all(ui_Container5);
lv_obj_set_width( ui_Container5, 170);
lv_obj_set_height( ui_Container5, 20);
lv_obj_set_x( ui_Container5, -50 );
lv_obj_set_y( ui_Container5, 66 );
lv_obj_set_align( ui_Container5, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_Container5);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"1/10");
lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_Screen2_screen_destroy(void)
{
   if (ui_Screen2) lv_obj_del(ui_Screen2);

// NULL screen variables
ui_Screen2= NULL;
ui_Container1= NULL;
ui_title= NULL;
ui_content= NULL;
ui_Container5= NULL;
ui_Label3= NULL;

}
