// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: wf_ui

#ifndef _WF_UI_UI_H
#define _WF_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_1156340770);   // assets/icons8-notification-24.png
LV_IMG_DECLARE( ui_img_charge_png);   // assets/charge.png
LV_IMG_DECLARE( ui_img_battery_status_4_png);   // assets/battery_status_4.png
LV_IMG_DECLARE( ui_img_sun_png);   // assets/sun.png
LV_IMG_DECLARE( ui_img_battery_status_0_png);   // assets/battery_status_0.png
LV_IMG_DECLARE( ui_img_battery_status_1_png);   // assets/battery_status_1.png
LV_IMG_DECLARE( ui_img_battery_status_2_png);   // assets/battery_status_2.png
LV_IMG_DECLARE( ui_img_battery_status_3_png);   // assets/battery_status_3.png
LV_IMG_DECLARE( ui_img_battery_status_5_png);   // assets/battery_status_5.png
LV_IMG_DECLARE( ui_img_moon_png);   // assets/moon.png

// FONTS
LV_FONT_DECLARE( ui_font_NotoSansCondensedMedium);
LV_FONT_DECLARE( ui_font_sevensegments);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
